name: CustomFactions
version: ${project.version}
main: esp.lbelmar.customfactions.CustomFactions
api-version: 1.17
authors: [ LuisBelloch ]
description: Configure factions, chests access and more

commands:
  createFaction:
    description: Create a new faction
    usage: /createFaction
    permission: minecraft.command.help
  invitation:
    description: Accept of deny an invitation to a faction
    usage: /invitation
    permission: minecraft.command.help
  invitePlayer:
    description: Invite a player to your faction
    usage: /invitePlayer
    permission: minecraft.command.help
  factionMembers:
    description: Get all members of a faction
    usage: /factionMembers
    permission: minecraft.command.help
  banishPlayer:
    description: Banish a player from your faction
    usage: /banishPlayer
    permission: minecraft.command.help
  claimChunk:
    description: Claim a chunk for your faction
    usage: /claimChunk
    permission: minecraft.command.help
  msgFaction:
    description: Send a message to all your faction
    usage: /msgFaction
    permission: minecraft.command.help
